export const SEND_MESSAGE = 'carbon:send-filled'
export const CHAT_MESSAGE_SENDING = 'svg-spinners:gooey-balls-1'
export const SETTING = 'carbon:settings'
export const HEART_ZERO = 'carbon:favorite'
export const HEART_CHARGING = 'carbon:favorite-half'
export const HEART_FULL = 'carbon:favorite-filled'
