export const SEND_MESSAGE = 'carbon:send-filled'
export const CHAT_MESSAGE_SENDING = 'svg-spinners:gooey-balls-1'
export const SETTING = 'twemoji:gear'
export const HEART_ZERO = 'twemoji:mending-heart'
export const HEART_CHARGING = 'twemoji:purple-heart'
export const HEART_FULL = 'twemoji:red-heart'
