POST http://localhost:3000/api/aimigos
Content-Type: application/json

{
  "name": "폼폼푸린3",
  "mbti": "INFP",
  "oauthId": "1234567890"
}

###
GET http://localhost:3000/api/aimigos

###
GET http://localhost:3000/api/users
